name: 'ae_exam'
version: '1.0.0'

profile: 'ae_exam_db' # Changed this line

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

#target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"


models:
  ae_exam:
    example:
      +materialized: view
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: marts
      +materialized: table
    reports:
      +schema: reports
      +materialized: view